flags:
  text:
    integer-simple: false
packages:
- '.'
extra-deps:
- MonadRandom-0.4
- QuickCheck-2.8.1
- async-2.0.2
- constraints-0.4.1.3
- hashable-1.2.3.3
- lifted-async-0.7.0.1
- lifted-base-0.2.3.6
- monad-control-1.0.0.4
- mtl-2.2.1
- mwc-random-0.13.3.2
- newtype-0.2
- primitive-0.6.1.0
- random-1.1
- random-shuffle-0.0.4
- repa-3.4.0.1
- stm-2.4.4
- text-1.2.1.3
- tf-random-0.5
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- unordered-containers-0.2.5.1
- vector-0.10.12.3
- vector-algorithms-0.7.0.1
resolver: ghc-7.10.2
