flags:
  text:
    integer-simple: false
packages:
- '.'
extra-deps:
- MonadRandom-0.4
- QuickCheck-2.8.1
- StateVar-1.1.0.1
- adjunctions-4.2.2
- base-orphans-0.4.4
- bifunctors-5
- comonad-4.2.7.2
- contravariant-1.3.3
- data-default-class-0.0.1
- distributive-0.4.4
- dlist-0.7.1.2
- dlist-instances-0.1
- exceptions-0.8.0.2
- free-4.12.1
- hashable-1.2.3.3
- kan-extensions-4.2.3
- keys-3.10.2
- mono-traversable-0.10.0
- mtl-2.2.1
- mwc-random-0.13.3.2
- nats-1
- pointed-4.2.0.2
- prelude-extras-0.4.0.2
- primitive-0.6.1.0
- profunctors-5.1.1
- random-1.1
- random-shuffle-0.0.4
- semigroupoids-5.0.0.4
- semigroups-0.17.0.1
- split-0.2.2
- stm-2.4.4
- tagged-0.8.1
- text-1.2.1.3
- tf-random-0.5
- transformers-compat-0.4.0.4
- unordered-containers-0.2.5.1
- vector-0.11.0.0
- vector-algorithms-0.7.0.1
- vector-instances-3.3.1
- void-0.7.1
resolver: ghc-7.10.2
